<template>
  <div class="custom-loading">
    <svg
      id="Capa_1"
      data-name="Capa 1"
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      viewBox="0 0 150 150"
      width="150"
      height="150"
    >
      <svg
        width="150"
        height="150"
        viewBox="0 0 44 44"
        xmlns="http://www.w3.org/2000/svg"
        stroke="#000"
      >
        <g fill="none" fill-rule="evenodd" stroke-width="2">
          <circle cx="22" cy="22" r="1">
            <animate
              attributeName="r"
              begin="0s"
              dur="1s"
              values="1; 20"
              calcMode="spline"
              keyTimes="0; 1"
              keySplines="0.165, 0.84, 0.44, 1"
              repeatCount="indefinite"
            />
            <animate
              attributeName="stroke-opacity"
              begin="0s"
              dur="1s"
              values="1; 0"
              calcMode="spline"
              keyTimes="0; 1"
              keySplines="0.3, 0.61, 0.355, 1"
              repeatCount="indefinite"
            />
          </circle>
          <circle cx="22" cy="22" r="1">
            <animate
              attributeName="r"
              begin="-0.9s"
              dur="1.8s"
              values="1; 20"
              calcMode="spline"
              keyTimes="0; 1"
              keySplines="0.165, 0.84, 0.44, 1"
              repeatCount="indefinite"
            />
            <animate
              attributeName="stroke-opacity"
              begin="-0.9s"
              dur="1.8s"
              values="1; 0"
              calcMode="spline"
              keyTimes="0; 1"
              keySplines="0.3, 0.61, 0.355, 1"
              repeatCount="indefinite"
            />
          </circle>
        </g>
      </svg>
      <defs>
        <mask id="mask" x="21.54" y="22.47" width="106" height="106" maskUnits="userSpaceOnUse">
          <g id="mask0">
            <rect
              x="21.54"
              y="22.47"
              width="106"
              height="53"
              fill="#c4c4c4"
              class="svg-elem-1"
            ></rect>
          </g>
        </mask>
      </defs>
      <circle
        cx="74.54"
        cy="75.47"
        r="51"
        fill="#fff"
        stroke="#333"
        stroke-width="4"
        class="svg-elem-2"
      ></circle>
      <g mask="url(#mask)">
        <circle
          cx="74.54"
          cy="75.47"
          r="51"
          fill="#f22539"
          stroke="#333"
          stroke-width="4"
          class="svg-elem-3"
        ></circle>
      </g>
      <path
        d="M21.93,75.47H127.15"
        fill="none"
        stroke="#333"
        stroke-width="4"
        class="svg-elem-4"
      ></path>
      <circle cx="74.54" cy="75.47" r="20.81" fill="#fff" class="svg-elem-5"></circle>
      <circle
        cx="74.54"
        cy="75.47"
        r="18.81"
        fill="none"
        stroke="#333"
        stroke-width="4"
        class="svg-elem-6"
      ></circle>
      <path
        id="rotate-infinite-change-color"
        d="M113.27,59.17A42.12,42.12,0,0,0,86.91,35.31"
        fill="none"
        stroke="#fff"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="4"
        class="svg-elem-7"
      >
        <animateTransform
          attributeName="transform"
          type="rotate"
          from="0 74.54 74.54"
          to="360 74.54 74.54"
          begin="0"
          dur="1s"
          repeatCount="indefinite"
        ></animateTransform>
      </path>
      <circle
        cx="74.54"
        cy="75.47"
        r="10.39"
        fill="none"
        stroke="gray"
        stroke-width="2"
        class="svg-elem-8"
      ></circle>
    </svg>
  </div>
</template>
<style scoped>
.custom-loading {
  background-color: black;
  display: flex;
  align-items: center;
  justify-content: center;
  position: fixed;
  width: 100%;
  height: 100vh;
  top: 0;
  left: 0;
  z-index: 5;
}
svg {
  display: block;
}
#rotate-infinite-change-color {
  animation: change-color 1s infinite;
}
@keyframes change-color {
  0% {
    stroke: white;
  }
  21% {
    stroke: white;
  }
  62% {
    stroke: red;
  }
  100% {
    stroke: white;
  }
}
/***************************************************
 * Generated by SVG Artista on 7/14/2021, 11:37:26 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/
@-webkit-keyframes animate-svg-stroke-1 {
  0% {
    stroke-dashoffset: 320px;
    stroke-dasharray: 320px;
  }
  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 320px;
  }
}
@keyframes animate-svg-stroke-1 {
  0% {
    stroke-dashoffset: 320px;
    stroke-dasharray: 320px;
  }
  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 320px;
  }
}
@-webkit-keyframes animate-svg-fill-1 {
  0% {
    fill: transparent;
  }
  100% {
    fill: rgb(196, 196, 196);
  }
}
@keyframes animate-svg-fill-1 {
  0% {
    fill: transparent;
  }
  100% {
    fill: rgb(196, 196, 196);
  }
}
.svg-elem-1 {
  -webkit-animation:
    animate-svg-stroke-1 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) 0s both,
    animate-svg-fill-1 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
  animation:
    animate-svg-stroke-1 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) 0s both,
    animate-svg-fill-1 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
}
@-webkit-keyframes animate-svg-stroke-2 {
  0% {
    stroke-dashoffset: 322.4424506661589px;
    stroke-dasharray: 322.4424506661589px;
  }
  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 322.4424506661589px;
  }
}
@keyframes animate-svg-stroke-2 {
  0% {
    stroke-dashoffset: 322.4424506661589px;
    stroke-dasharray: 322.4424506661589px;
  }
  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 322.4424506661589px;
  }
}
@-webkit-keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }
  100% {
    fill: rgb(255, 255, 255);
  }
}
@keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }
  100% {
    fill: rgb(255, 255, 255);
  }
}
.svg-elem-2 {
  -webkit-animation:
    animate-svg-stroke-2 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s both,
    animate-svg-fill-2 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
  animation:
    animate-svg-stroke-2 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s both,
    animate-svg-fill-2 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
}
@-webkit-keyframes animate-svg-stroke-3 {
  0% {
    stroke-dashoffset: 322.4424506661589px;
    stroke-dasharray: 322.4424506661589px;
  }
  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 322.4424506661589px;
  }
}
@keyframes animate-svg-stroke-3 {
  0% {
    stroke-dashoffset: 322.4424506661589px;
    stroke-dasharray: 322.4424506661589px;
  }
  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 322.4424506661589px;
  }
}
@-webkit-keyframes animate-svg-fill-3 {
  0% {
    fill: transparent;
  }
  100% {
    fill: rgb(242, 37, 57);
  }
}
@keyframes animate-svg-fill-3 {
  0% {
    fill: transparent;
  }
  100% {
    fill: rgb(242, 37, 57);
  }
}
.svg-elem-3 {
  -webkit-animation:
    animate-svg-stroke-3 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s both,
    animate-svg-fill-3 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
  animation:
    animate-svg-stroke-3 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s both,
    animate-svg-fill-3 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
}
@-webkit-keyframes animate-svg-stroke-4 {
  0% {
    stroke-dashoffset: 107.22000122070312px;
    stroke-dasharray: 107.22000122070312px;
  }
  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 107.22000122070312px;
  }
}
@keyframes animate-svg-stroke-4 {
  0% {
    stroke-dashoffset: 107.22000122070312px;
    stroke-dasharray: 107.22000122070312px;
  }
  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 107.22000122070312px;
  }
}
.svg-elem-4 {
  -webkit-animation:
    animate-svg-stroke-4 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s both,
    animate-svg-fill-4 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s both;
  animation:
    animate-svg-stroke-4 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s both,
    animate-svg-fill-4 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s both;
}
@-webkit-keyframes animate-svg-stroke-5 {
  0% {
    stroke-dashoffset: 132.7530862424072px;
    stroke-dasharray: 132.7530862424072px;
  }
  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 132.7530862424072px;
  }
}
@keyframes animate-svg-stroke-5 {
  0% {
    stroke-dashoffset: 132.7530862424072px;
    stroke-dasharray: 132.7530862424072px;
  }
  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 132.7530862424072px;
  }
}
@-webkit-keyframes animate-svg-fill-5 {
  0% {
    fill: transparent;
  }
  100% {
    fill: rgb(255, 255, 255);
  }
}
@keyframes animate-svg-fill-5 {
  0% {
    fill: transparent;
  }
  100% {
    fill: rgb(255, 255, 255);
  }
}
.svg-elem-5 {
  -webkit-animation:
    animate-svg-stroke-5 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s both,
    animate-svg-fill-5 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s both;
  animation:
    animate-svg-stroke-5 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s both,
    animate-svg-fill-5 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s both;
}
@-webkit-keyframes animate-svg-stroke-6 {
  0% {
    stroke-dashoffset: 120.186715628048px;
    stroke-dasharray: 120.186715628048px;
  }
  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 120.186715628048px;
  }
}
@keyframes animate-svg-stroke-6 {
  0% {
    stroke-dashoffset: 120.186715628048px;
    stroke-dasharray: 120.186715628048px;
  }
  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 120.186715628048px;
  }
}
.svg-elem-6 {
  -webkit-animation:
    animate-svg-stroke-6 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s both,
    animate-svg-fill-6 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s both;
  animation:
    animate-svg-stroke-6 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s both,
    animate-svg-fill-6 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s both;
}
@-webkit-keyframes animate-svg-stroke-7 {
  0% {
    stroke-dashoffset: 38.705501556396484px;
    stroke-dasharray: 38.705501556396484px;
  }
  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 38.705501556396484px;
  }
}
@keyframes animate-svg-stroke-7 {
  0% {
    stroke-dashoffset: 38.705501556396484px;
    stroke-dasharray: 38.705501556396484px;
  }
  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 38.705501556396484px;
  }
}
.svg-elem-7 {
  -webkit-animation:
    animate-svg-stroke-7 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) 0.72s both,
    animate-svg-fill-7 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4000000000000001s both;
  animation:
    animate-svg-stroke-7 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) 0.72s both,
    animate-svg-fill-7 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4000000000000001s both;
}
@-webkit-keyframes animate-svg-stroke-8 {
  0% {
    stroke-dashoffset: 67.2822953415959px;
    stroke-dasharray: 67.2822953415959px;
  }
  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 67.2822953415959px;
  }
}
@keyframes animate-svg-stroke-8 {
  0% {
    stroke-dashoffset: 67.2822953415959px;
    stroke-dasharray: 67.2822953415959px;
  }
  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 67.2822953415959px;
  }
}
.svg-elem-8 {
  -webkit-animation:
    animate-svg-stroke-8 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) 0.84s both,
    animate-svg-fill-8 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s both;
  animation:
    animate-svg-stroke-8 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) 0.84s both,
    animate-svg-fill-8 0.2s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s both;
}
</style>
