# Simple workflow for deploying static content to GitHub Pages
name: Tests E2E

on:
  # Runs on pushes targeting the default branch
  pull_request:

jobs:
  # Single deploy job since we're just deploying
  runing-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
        env:
          VITE_BASE_URL: ${{ vars.BASE_URL }}
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Running Test e2e
        run: |
          npm run test:e2e